---
# Grafana Configuration
grafana_version: "10.2.0"
grafana_admin_user: "admin"
grafana_admin_password: "securepassword123"
grafana_port: 3000

# Prometheus Configuration
prometheus_host: "aaa"
prometheus_port: 9090

# System Configuration
grafana_data_dir: "/var/lib/grafana"
grafana_log_dir: "/var/log/grafana"
