---
- name: Install and configure Prometheus with Blackbox Exporter
  hosts: prometheus
  become: true
  vars:
    prometheus_version: "2.53.0"
    blackbox_version: "0.25.0"
    prometheus_dir: /etc/prometheus
    prometheus_data_dir: /var/lib/prometheus
    website_to_probe: "https://fbref.com/en/comps/9/Premier-League-Stats#all_results2025-202691 "

  tasks:

  - name: Ensure required packages are installed
    apt:
      name:
        - wget
        - tar
      update_cache: yes

  - name: Create Prometheus user
    user:
      name: prometheus
      shell: /usr/sbin/nologin
      system: yes
      create_home: no

  - name: Create directories for Prometheus
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
      - "{{ prometheus_dir }}"
      - "{{ prometheus_data_dir }}"

  - name: Download and extract Prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      dest: /tmp
      remote_src: yes
      creates: /usr/local/bin/prometheus


  - name: Download Prometheus on remote host
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v2.53.0/prometheus-2.53.0.linux-amd64.tar.gz"
      dest: /tmp/prometheus.tar.gz
      mode: '0755'

  - name: Extract Prometheus on remote host
    unarchive:
      src: /tmp/prometheus.tar.gz
      dest: /tmp/
      remote_src: yes

  - name: Move Prometheus binaries
    copy:
      src: "/tmp/prometheus-2.53.0.linux-amd64/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: '0755'
      remote_src: yes
    loop:
      - prometheus
      - promtool



  - name: Move Prometheus binaries
    copy:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: '0755'
      owner: prometheus
      group: prometheus
      remote_src: yes
    loop:
      - prometheus
      - promtool

  - name: Copy Prometheus config
    template:
      src: templates/prometheus.yml.j2
      dest: "{{ prometheus_dir }}/prometheus.yml"
      owner: prometheus
      group: prometheus
      mode: '0644'

  - name: Create Prometheus systemd service
    copy:
      dest: /etc/systemd/system/prometheus.service
      content: |
        [Unit]
        Description=Prometheus
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/usr/local/bin/prometheus \
          --config.file={{ prometheus_dir }}/prometheus.yml \
          --storage.tsdb.path={{ prometheus_data_dir }}

        [Install]
        WantedBy=multi-user.target

  - name: Install Blackbox Exporter
    unarchive:
      src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_version }}/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz"
      dest: /tmp
      remote_src: yes
      creates: /usr/local/bin/blackbox_exporter

  - name: Move Blackbox Exporter binary
    copy:
      src: "/tmp/blackbox_exporter-{{ blackbox_version }}.linux-amd64/blackbox_exporter"
      dest: /usr/local/bin/blackbox_exporter
      mode: '0755'
      remote_src: yes

  - name: Copy Blackbox Exporter config
    template:
      src: templates/blackbox.yml.j2
      dest: "{{ prometheus_dir }}/blackbox.yml"
      owner: prometheus
      group: prometheus
      mode: '0644'

  - name: Create Blackbox Exporter systemd service
    copy:
      dest: /etc/systemd/system/blackbox_exporter.service
      content: |
        [Unit]
        Description=Blackbox Exporter
        After=network.target

        [Service]
        ExecStart=/usr/local/bin/blackbox_exporter \
          --config.file={{ prometheus_dir }}/blackbox.yml
        User=prometheus
        Restart=always

        [Install]
        WantedBy=multi-user.target

  - name: Enable and start services
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    loop:
      - blackbox_exporter
      - prometheus
