---
- name: Install and Configure Grafana with Prometheus Datasource
  hosts: grafana_servers
  become: yes
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"


    - name: Install prerequisites
      package:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Grafana APT repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana
      when: ansible_os_family == "Debian"

    - name: Install Grafana
      package:
        name: grafana={{ grafana_version }}
        state: present

    - name: Create Grafana directories
      file:
        path: "{{ item }}"
        state: directory
        owner: grafana
        group: grafana
        mode: '0755'
      loop:
        - "{{ grafana_data_dir }}"
        - "{{ grafana_log_dir }}"
        - /etc/grafana/provisioning/datasources

    - name: Configure Grafana main configuration
      template:
        src: templates/grafana.ini.j2
        dest: /etc/grafana/grafana.ini
        owner: root
        group: grafana
        mode: '0640'
      notify: restart grafana

    - name: Configure Prometheus datasource
      template:
        src: templates/datasource-prometheus.yml.j2
        dest: /etc/grafana/provisioning/datasources/prometheus.yml
        owner: root
        group: grafana
        mode: '0644'
      notify: restart grafana

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for Grafana to start
      wait_for:
        port: "{{ grafana_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60
        state: started

    - name: Display Grafana access information
      debug:
        msg: |
          Grafana has been installed and configured successfully!
          Access URL: http://{{ ansible_default_ipv4.address }}:{{ grafana_port }}
          Username: {{ grafana_admin_user }}
          Password: {{ grafana_admin_password }}
          Prometheus datasource configured at: http://{{ prometheus_host }}:{{ prometheus_port }}


  handlers:
    - name: restart grafana
      service:
        name: grafana-server
        state: restarted

    - name: Restart Grafana if config changed
      systemd:
        name: grafana-server
        state: restarted
      when: config_changed.changed

    - name: Create dashboard directory
      file:
        path: /var/lib/grafana/dashboards
        state: directory
        owner: grafana
        group: grafana
        mode: '0755'

    - name: Configure dashboard provisioning
      template:
        src: templates/dashboard.yml.j2
        dest: /etc/grafana/provisioning/dashboards/default.yml
        owner: root
        group: grafana
        mode: '0644'
      notify: restart grafana
